In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv("../data/data.csv")
df.head()

In [ ]:
df.shape

In [ ]:
df.columns

In [ ]:
df.info()

In [ ]:
df.describe(include="all")

In [ ]:
df.isna().sum()

In [ ]:
df.duplicated().sum()

In [ ]:
df.nunique()

In [ ]:
df["Sales"].describe()

In [ ]:
df["Category"].value_counts()
# df["Segment"].value_counts()
# df["Region"].value_counts()
# df["Ship Mode"].value_counts()

In [37]:
df.dtypes
df[['Sales', 'Quantity', 'Discount', 'Profit']].corr()

             Sales  Quantity  Discount    Profit
Sales     1.000000 -0.001902  0.004972  0.003309
Quantity -0.001902  1.000000  0.014373  0.064227
Discount  0.004972  0.014373  1.000000 -0.215425
Profit    0.003309  0.064227 -0.215425  1.000000

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8, 6))

sns.heatmap(
    df[['Sales', 'Quantity', 'Discount', 'Profit']].corr(),
    annot=True,
    cmap='coolwarm'
)
plt.title("Matrice de correlation")
plt.show()

In [41]:
df.groupby('Segment')['Sales'].describe()
df.groupby('Segment')['Quantity'].describe()

              count      mean       std  min  25%  50%  75%   max
Segment
Consumer     5064.0  3.753752  2.210613 -5.0  2.0  3.0  5.0  14.0
Consumerr      57.0  4.070175  2.374415  1.0  2.0  3.0  5.0  11.0
Corporate    2953.0  3.839824  2.268050 -5.0  2.0  3.0  5.0  14.0
Corporrate     26.0  3.307692  2.054638  1.0  2.0  2.5  4.0  10.0
Home Office  1749.0  3.755289  2.274531 -5.0  2.0  3.0  5.0  14.0
Home Ofice     16.0  3.625000  2.334524  1.0  2.0  3.0  4.0   9.0